### ISSUE TITLE
EasyZoom jquery plugin not working

### ISSUE THREAD

**Issue by sandyrewa** [i-like-robots/EasyZoom#101]
@i-like-robots 
I have added jQuery EasyZoom plugin on my website and include easyzoom.css file after that zoom panel appear on right place but without any zoom, you can see below link - 

     http://clients.alphawebsol.com/zanzis/today/jf_6641/

But if i remove easyzoom.css file image zoom showing big image on whole screen.
Can anyone help me?

**Comment by i-like-robots** [comment]
Your zoom image is only 11% larger than your standard images. As mentioned in #99 I would recommend that the zoom image is _at least_ 50% larger than the standard image.

**Comment by sandyrewa** [comment]
@i-like-robots 
My image is larger if i didn't apply easyzoom.css then my image is showing very large but after add easyzoom.css it showing smaller as you now see

**Comment by i-like-robots** [comment]
Here is the standard image I see: http://clients.alphawebsol.com/zanzis/wp-content/uploads/2016/11/JF_6641-600x800.jpg

And this is the zoom image:  http://clients.alphawebsol.com/zanzis/wp-content/uploads/2016/11/JF_6641.jpg

The standard image dimensions are 600x800 and the zoom image is 667x1000

Given this, the component is working as expected. I would recommend your zoom image should be _a minimum_ of 900 pixels wide to really benefit from using the component.

**Comment by sandyrewa** [comment]
@i-like-robots 
I have just removed easyzoom.css file can you please look into it

**Comment by i-like-robots** [comment]
Out of the box I'm afraid EasyZoom only supports displaying images at their native size.

**Comment by sandyrewa** [comment]
@i-like-robots 
I think you understand my problem if i simple add easyzoom then it working fine without any css but after add css it's not working, so can you please suggest me what can i do to fix this?

**Comment by i-like-robots** [comment]
You have a rule in your CSS:

```css
.woocommerce div.product div.images img {
  display: block;
  width: 100%;
  height: auto;
  box-shadow: none;
}
```

This is applied to the zoom image which makes it the same width as its offset parent.

_Before_ you add the EasyZoom styles the offset parent is the element`div#product-341` which is the width of the viewport - 400px.

_After_ you apply the EasyZoom styles the offset parent becomes the 'flyout' element which is of equal size to the standard image.

You can adjust the styles of the flyout element (`.easyzoom-flyout`) to change its positioning and size.

**Comment by anaccna** [comment]
@i-like-robots 
I have also the same issue can you please elaborate the above step u mentioned.

**Comment by taurgal** [comment]
Just add `.easyzoom-flyout img {
  max-width: auto;
}` to your css style file and you should be fine.

**Comment by taurgal** [comment]
Just add `.easyzoom-flyout img { max-width: none; }` and you should be fine.
