### ISSUE TITLE
NPM package not found

### ISSUE THREAD

**Issue by XmlmXmlmX** [i-like-robots/EasyZoom#102]
Hi, I can't find ```EasyZoom``` at npmjs.com: https://www.npmjs.com/search?q=easyzoom&page=1&ranking=optimal (only hexo-easyzoomintijk and easyzoom-mp??)

By the way, the package name ```EasyZoom``` is [not valid](https://docs.npmjs.com/files/package.json#name).

> New packages must not have uppercase letters in the name.

**Comment by i-like-robots** [comment]
This package is not currently available via NPM (though I see somebody has mirrored it there). It's no problem to register it so I may do soon.

**Comment by i-like-robots** [comment]
Fixed in 5aebb287a5c5b8118ef23dc5c6a670b7972545c7

**Comment by XmlmXmlmX** [comment]
Thank you 👍
