### ISSUE TITLE
Needs touch support

### ISSUE THREAD

**Issue by ShadowXVII** [i-like-robots/EasyZoom#104]
Touching moves the picture but in the inverse direction (correct for mouse, but touch needs to be reversed).

Using this on my phone, my "touch instinct" is to drag/pan the picture around.

**Comment by ShadowXVII** [comment]
Just to clarify, using this on my phone, my "touch instinct" is to drag/pan the picture around

**Comment by i-like-robots** [comment]
Interesting idea, I'm not sure myself... I don't mind the way it works currently.

If you could spare the time to try it out I'd be very grateful.
