### ISSUE TITLE
Hover from left side (former #44)

### ISSUE THREAD

**Issue by rbnmo** [i-like-robots/EasyZoom#107]
Hi! Great plugin!

Only on Google Chrome, when entering hover from left or top slowly, it doesn't trigger the overlay.
Works great on other browsers.

**Comment by i-like-robots** [comment]
I can't re-create this issue with the demo...

![zoom](https://cloud.githubusercontent.com/assets/271645/23667410/aab5bcc4-0355-11e7-9fa0-e474a6c2b171.gif)

Are you able to setup a test case on Codepen?

**Comment by rbnmo** [comment]
I'm not sure I can replicate it on codepen, but I'll give you a link to the project I'm working on:
https://goo.gl/sOrl2G

It's a bit weird because it may have something to do with image size and browser window size. The first 2 images have this problem, the last 2 work just fine - on 1920x1080px resolution. 
If I resize the browser, the problem disappears on some resolutions and comes back on others, sometimes on entering from the left side and sometimes on entering from the top side.

**Comment by mihalikv** [comment]
Hello,

i have a same problem and after few minutes of debugging i figured out that flyout is hidden right after showing in these piece of code:
`if (xl < 0 || xt < 0 || xl > dw || xt > dh) {
    this.hide();
}`
Some how there is problem with float number imho. 

For fast fix you can remove this three lines and `mouseleave` take care about flyout hiding.

**Comment by i-like-robots** [comment]
That's right @mihalikv - I wish I'd named the variables better - but the `xl` and `xt` conditions you bring up do some to be troublesome.

@rbnmo I've found this is exacerbated by the border you have on the parent element. I'm afraid I haven't worked out why, yet.

**Comment by rbnmo** [comment]
True, if you have the dev console/tools open and remove that css border, it fixes it. But if you close the console right after that and test it, the problem is actually still there. So I think it has to do with the window size? Try dragging the window size back and forth and you'll find that the problem pops in and out based on window width (I keep the dev tools to the right of the window and drag it left-right).

**Comment by i-like-robots** [comment]
I haven't had time to investigate this any further yet, something is being miscalculated. I can't think why a border would exacerbate the issue but it deepens the mystery!

**Comment by mihalikv** [comment]
@i-like-robots i still thinks that there is no need to have that if at all, because mouseleave event take care about hiding of flyout element. If you remove that if else statement everything work fine. What do you think about that ?

**Comment by i-like-robots** [comment]
@mihalikv Worth a try... this is why it was added: https://github.com/i-like-robots/EasyZoom/issues/19

**Comment by i-like-robots** [comment]
Fixed in #120
