### ISSUE TITLE
Zoom Adjacent on desktop overlay on mobile

### ISSUE THREAD

**Issue by piotrbox** [i-like-robots/EasyZoom#110]
Hi, do You know any way to toggle between adjacent and overlay on mobile vs desktop. It is activated by class so do I need to change classes activly with js? ~~will this work?~~ it will, but looks kinda dirty.
or is there a way to activate proper mode only by js?

**Comment by i-like-robots** [comment]
The class names are only CSS hooks, so if you modify the default CSS to use "overlay" by default and move the "adjacent" styles inside a media query for larger screens that should do the trick.

**Comment by piotrbox** [comment]
Great! Didn't think of that, Thanx a lot!
