### ISSUE TITLE
Max-width and max hight.

### ISSUE THREAD

**Issue by PanSom** [i-like-robots/EasyZoom#112]
PLZ add css
.easyzoom-flyout  img {
  max-width: inherit;
  max-height: inherit;
}

**Comment by i-like-robots** [comment]
Hello @PanSom, thank you for your question. Could you please provide an example why you think this change may be required?

**Comment by madeelahsan** [comment]
thanks, @PanSom. flyout image height was shrinking on hover and didn't get proper position. but this property resolves it.

**Comment by mfronczyk** [comment]
I had to include it as well (setting them to "none" instead of "inherit" also works). In my case it was the Foundation framework which sets max-width: 100% for every image and we had to reset it.

**Comment by i-like-robots** [comment]
Glad you were able to fix it.
