### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by vastril4o** [i-like-robots/EasyZoom#118]
copy the js and css and add in mine project, set the two images as in the example and nothing, only the cursor is changed. Also its not clear in the example which is the large and which is the small, you have use the words "zoom" and "standard", why don`t you use small and large?

**Comment by colinxr** [comment]
You should set the the larger image in the `a` tag -- where the 'zoom.jpg' is set in the example. Zoom is the larger of the two images and standard is the normal size.

**Comment by zdimaz** [comment]
/* =============================================
		4.13 EasyZoom
	============================================= */

		.easyzoom {
			position: relative;
		}

		.easyzoom > a{
			display: block;
		}

		.easyzoom > a > img {
			max-height: 100%;
		}

		.easyzoom.is-loading img {
			cursor: progress;
		}

		.easyzoom.is-ready img {
			cursor: crosshair;
		}

		.easyzoom.is-error  img {
			cursor: not-allowed;
		}

		.easyzoom-flyout {
			position: absolute;
			top: 0;
			right: 0;
			left: 0;
			bottom: 0;
			overflow: hidden;
			background: #FFF;
			width: 100%;
			height: 100%;
		}

		.easyzoom-flyout > img{
			max-width: initial !important;
			width: auto !important;
			-webkit-transition: 0.1s linear;
			-o-transition: 0.1s linear;
			transition: 0.1s linear;
		}

**Comment by amichel86** [comment]
How did you make it work? I copied and pasted the example from the home page but the image doesn’t zoom when hovering :(
