### ISSUE TITLE
preventClicks false

### ISSUE THREAD

**Issue by fburatti** [i-like-robots/EasyZoom#126]
Great plugin and simple to implement.
However I can not use the preventClicks option (false) with "easyzoom--overlay" mode: the click on the  zoom image link still does not work

**Comment by i-like-robots** [comment]
Thanks for your nice words @fburatti.

To ensure clicks are able to "pass through" the overlay element to the underlying link element you can add a `pointer-events` property to the element, like this:


```diff
.easyzoom-flyout--overlay {
+	pointer-events: none;
}
```
