### ISSUE TITLE
disable plugin on touch devices

### ISSUE THREAD

**Issue by vd1216** [i-like-robots/EasyZoom#129]
is it possible to disable it on touch devices ?
i can't find any documentation about it(((((((((

**Comment by zevnikrok** [comment]
I am also looking how to disable it on touch device.
Or even better, how to be able to scroll the page with dragging over the image (now it zooms in).

**Comment by vd1216** [comment]
@zevnikrok i used css pointer-events: none; with media queries. 
and it works as i needed
