### ISSUE TITLE
teardown and init doesn't refresh all zoomables

### ISSUE THREAD

**Issue by sezginriggs** [i-like-robots/EasyZoom#130]
Hello,

I'm loading multiple zoomables (on same page) with
```
    var $easyzoom = $('.easyzoom').easyZoom({
        loadingNotice: 'Loading...'
    });

    var easyZoomApi = $easyzoom.data('easyZoom');
```

it works fine when their src or href not changed but after (for example after rotating image etc.) trying to refresh their unzoomed and zoomed images with

```
        easyZoomApi.teardown();
        easyZoomApi._init();
```
unfortunately it refreshes zoom image for the first image and not others. How can I refresh all?

**Comment by i-like-robots** [comment]
The `.data()` method will only return data for the first element, from the docs:

> returns the value at the named data store for the first element in the set of matched elements.

So you'll need to iterate over each element in the set:

```js
$easyzoom.each((i) => {
  $easyzoom.eq(i).data('easyZoom').teardown();
});
```
