### ISSUE TITLE
Image doesn't zoom

### ISSUE THREAD

**Issue by amichel86** [i-like-robots/EasyZoom#133]
Hi there and thanks for your plugin. I followed every steps but I can't seem to have the plugin working. When I hover the image it just scales (bigger image loads) but doesn't zoom. I took your most recent JS and CSS. Do you know what can be missing?

Video: https://www.youtube.com/watch?v=PXMGP_XdRGs

Thanks! :D

**Comment by Navneet61940** [comment]
@i-like-robots, 
Same problems i have faced. can you fixed it?

**Comment by amichel86** [comment]
@Navneet61940 I fixed it but I don't remember how since it's been more than 2 years, you can inspect my code here:

https://collegesaintsacrement.qc.ca/bienvenue-portes-ouvertes#visite-10

**Comment by Navneet61940** [comment]
@amichel86  I from India, so this link is not working in India not able to view this website.
I have try with proxy than it opened but not found on inspect anything related to easy zoom.
    
Thank you for your help!

**Comment by amichel86** [comment]
@Navneet61940 don't know if this gonna help but here's the HTML and JS snippets

`<div class="zoom" style="position: relative;overflow: hidden;">
  <img src="smaller-image.jpg" alt="">
	<img role="presentation" alt="" src="bigger-image.jpg" class="zoomImg">
</div>`

`$('.zoom').zoom();`
