### ISSUE TITLE
Easy zoom not working properly on my website

### ISSUE THREAD

**Issue by amarThakur** [i-like-robots/EasyZoom#15]
Check this link -->
http://www.bangurnagar.com/displayDetails.php?type=SHOPPING&value=class/ProductDetailClass/shoppingProducts//Medicines%20Cabinet/Pentene.txt

For those images easy zoom not working.
Please revert fast.
Thanks for simple Jquery for image zoom.

**Comment by SergyCh** [comment]
In my case, there was missing css-style "layout variations": .easyzoom--overlay or .asyzoom--adjacent. I added these and it works fine now))
