### ISSUE TITLE
Multiple images

### ISSUE THREAD

**Issue by chaluvadiswamy** [i-like-robots/EasyZoom#25]
When i using the multiple images ,after changing the image the zoom image is considering first image instead of the selected image.when we try to callback _init() its not working

**Comment by performatric** [comment]
Probably I have the same issue. I'm using this plugin with Swiper plugin and works similar how the "With thumbnail" example, but the primary image is not only one image, is a gallery too.
I'm using this without img tag, but with backgroud-image property, with the first image works like a charm.
I put my code on Plunker:

http://plnkr.co/edit/yvfXcF9TCQOioNw9gDEP?p=preview

Anyone can help me, please! sorry my english (:
