### ISSUE TITLE
Embedded CSS

### ISSUE THREAD

**Issue by adelacameron** [i-like-robots/EasyZoom#59]
It appears that embedded CSS does function properly.  For example 

p>

 	div class="easyzoom easyzoom--overlay">
 		a href="images/1_zoom.jpg">
			<img src="images/1_standard.jpg" alt="" style="float:left; margin:0 5px 0 0;width:352px; height:403px;" />
		/a>
	/div>

This is text that should wrap around the image.....

/p>

**Comment by i-like-robots** [comment]
If you want text to wrap around the easyzoom instance you'll need to float the easyzoom `<div>` not its contents.
