### ISSUE TITLE
Teardown affects first image only

### ISSUE THREAD

**Issue by jjwilliamsza** [i-like-robots/EasyZoom#60]
Teardown via the api only removes the events off the first image on the page.

**Comment by i-like-robots** [comment]
Each instance of EasyZoom on the page has its own API so you will need to call `.teardown` on each instance.

When you access data on a collection jQuery will do so only for the first element (http://api.jquery.com/data/).

```js
var $zooms = $(".easyzoom");
$zooms.each(function(i) {
  $zooms.eq(i).data("easyZoom").teardown();
});
```
