### ISSUE TITLE
refresh function missing

### ISSUE THREAD

**Issue by uhb** [i-like-robots/EasyZoom#62]
I have a situation where I must update an image on the fly when the user changes a color.
 To make that work, I had to do the following, other tries did'nt work:
    <code>    function updateDetailsPageImages(current_product) {
            var newsrc = current_product.info['productimage'],
                    newimg = '<a href="' + newsrc + '"><img src="' + newsrc + '" width="400" height="300" /></a>';
            $("#productimage").html(newimg);
            var z = $(".easyzoom").easyZoom();
            var api = z.data('easyZoom');
            api.teardown();
            z = $('.easyzoom').easyZoom();
..... more
</code>

Shouldn't there be a more elegant way?

Thanks for consideration
Uwe

**Comment by i-like-robots** [comment]
Thanks for your question. Have you seen the `.swap()` method?

http://i-like-robots.github.io/EasyZoom/#api

**Comment by uhb** [comment]
yes, thank you. I thought is was just for interchanging big and small
image and did not think further.

Thanks again for your help
Uwe

Am 09.02.2015 um 07:39 schrieb Matt Hinchliffe:
> Thanks for your question. Have you seen the |.swap()| method?
> 
> http://i-like-robots.github.io/EasyZoom/#api
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/i-like-robots/EasyZoom/issues/62#issuecomment-73443068>.
> 

  * Thailändisch - erkannt
  * Englisch
  * Thailändisch
  * Deutsch

  * Englisch
  * Thailändisch
  * Deutsch

 <javascript:void(0);>

**Comment by uhb** [comment]
my target was: not so many lines of code..... as here:
$(".easyzoom").easyZoom().data('easyZoom').swap(newsrc, newsrc);
instead of 3 lines.

and, maybe useful for somebody else, to make it a little bit responsive, I added this css statement:
@media only screen and (max-width: 860px){
    .easyzoom--adjacent .easyzoom-flyout {
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        margin-left: 0px;
    }
