### ISSUE TITLE
/css/easyzoom.css is saved as 'UTF-8' (and not 'UTF-8 without BOM')

### ISSUE THREAD

**Issue by danielszabo** [i-like-robots/EasyZoom#63]
I have a compressed css file, that combines all my css files together (based on PHP includes). After adding /css/easyzoom.css, I had to convert the encoding of /css/easyzoom.css to 'UTF-8 without BOM' (from 'UTF-8'), otherwise it didn't work (unwanted '\ufeff' appeared at the beginning of the file).

I downloaded the files from http://i-like-robots.github.io/EasyZoom/.

**Comment by i-like-robots** [comment]
Thanks for the heads up @danielszabo
