### ISSUE TITLE
Tip: Foundation can keep image flyout from appearing

### ISSUE THREAD

**Issue by fform** [i-like-robots/EasyZoom#64]
I'm using Foundation 5 and EasyZoom 2.3.0.

Out of the box, Foundation sets a global rule for img tags of `max-width: 100%`. If you are trying to use the same image but with a css scale tranform, like
`.easyzoom-flyout img { transform: scale(2); }`
Then you'll need to make sure that images in the easyzoom don't have a max-width rule.

    .easyzoom-flyout img {
        transform: scale(2);
        max-width: none;
    } 

Otherwise, EasyZoom will trigger the show and then immediately the hide events. I didn't look through the code here but I'm guessing EasyZoom checks to see if it's necessary to zoom at all, or maybe it keeps the mouse move positioning from looking weird if the image isn't zoomed at all.

Hope this helps someone

**Comment by gembo** [comment]
Thank you so much for this, you've saved me a lot of time!

For me it was also that all my images were set to `width: 100%`, so I had to set `.easyzoom-flyout img` to `width: auto;`  aswell.
