### ISSUE TITLE
trigger double click before zooming

### ISSUE THREAD

**Issue by Alkasih** [i-like-robots/EasyZoom#65]
can you give another sample which has the function of triggering double click first before zooming the image, please?

**Comment by i-like-robots** [comment]
I've been asked a few times how to add an on/off toggle so maybe I should. It's very straightforward so I'm happy to accept any pull requests if you're up for it.

**Comment by jhollender** [comment]
First off, great plugin. However, I'm trying to disable mobile zoom until a user double taps on the image and I can't get it to work. Have you had any success with that?

**Comment by i-like-robots** [comment]
I have added a demo with an on/off toggle to the examples: http://i-like-robots.github.io/EasyZoom/

@jhollender Why not simply this?:

```js
$('.easyzoom').one('doubletap', function() {
  $(this).easyZoom();
});
```

There are lots of double click/double tap custom events available, or you can implement your own.

**Comment by jhollender** [comment]
Thanks for the info. Could you give me an example of how to make it disabled by default and click to enable the zoom? I can't quite get it to function properly.
