### ISSUE TITLE
Can you provide an example?

### ISSUE THREAD

**Issue by jhollender** [i-like-robots/EasyZoom#66]
Sorry to double-post, I just saw the other issue was closed. Would you be able to provide an example of EazyZoom disabled by default and toggle to enable the zoom? I can't quite get it to function properly.

**Comment by i-like-robots** [comment]
If you paste your code here I'll take a look.

**Comment by jhollender** [comment]
<div id="photos" class="galleryview">
  <div id="photos" class="easyzoom easyzoom--overlay">
    <a href="/large/PT4923A.jpg" class="big-photo"><img src="/medium/PT4923A.jpg" /></a>
  </div>
  <a class="toggle" data-active="true">Enable Zoom</a>
</div>

<script>
  var $easyzoom = $('.easyzoom').easyZoom();
  var api2 = $easyzoom.filter('.easyzoom--with-toggle').data('easyZoom');
  api2.teardown();

  $('.toggle').on('click', function() {
  var $this = $(this);

  if ($this.data("active") === true) {
    $this.text("Enable Zoom").data("active", false);
    api2._init();
  } else {
    $this.text("Disable Zoom").data("active", true);
    api2.teardown();
  }

});
</script>

**Comment by i-like-robots** [comment]
Take a look at what you're doing on the first few lines:

```js
var $easyzoom = $('.easyzoom').easyZoom();
```

So you're getting a collection of elements that match the selector and instantiating the plugin for each. The collection is being assigned to the variable `$easyzoom`;

```js
var api2 = $easyzoom.filter('.easyzoom--with-toggle').data('easyZoom');
```

You're filtering the collection gathered previously, retrieving the API for the first element in the collection and assigning it the the variable `api2`.

```js
api2.teardown();
```

You're tearing that instance down.

---

Here's what I'd suggest you do:

1. Don't instantiate plugin instances you're going to teardown immediately
2. Check there are elements matching the selector `.easyzoom--with-toggle`
3. Associate each toggle button with the easyzoom instance it is meant to control (E.G. using a data attribute, see below).

```js
$('.toggle').on('click', function() {
  var instanceID = $(this).data('controls');
  var api = $(instanceID).data('easyZoom');
  ...
});
```
