### ISSUE TITLE
What is wrong with my website

### ISSUE THREAD

**Issue by sahibvirk** [i-like-robots/EasyZoom#69]
Can anybody tell me where am i going wrong and what is wrong with my website that this plugin is not working.

http://cachetquo.com/index.php/men/wallets/leather-wallet-82.html#

**Comment by sahibvirk** [comment]
Please Help!!! Please!!!

**Comment by i-like-robots** [comment]
It looks like you've managed to resolve your issue =)

**Comment by sahibvirk** [comment]
Yup I had to understand and modify the source code of this plugin. I had to fix the height and width of the zoom image to what was required by my site. I know this fix was not a permanent one, but it just did my job for me. And the plugin looks great too. Thanks a lot................
