### ISSUE TITLE
Does not work on png files

### ISSUE THREAD

**Issue by agoranet** [i-like-robots/EasyZoom#70]
Does this only work with JPGs?  I'm using with different file types and it doesn't zoom on PNG files.

**Comment by rickduncan1956** [comment]
I'm using png but it seems to only work in FF and not Chrome or IE 11

**Comment by i-like-robots** [comment]
EasyZoom will work for any image type. If you're able to share an example demonstrating your image loading issues I may be able to help you solve them.
