### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by renzosalvador** [i-like-robots/EasyZoom#71]
Any way to control the speed of the zone being zoomed while going from top to bottom?

**Comment by i-like-robots** [comment]
Not at the moment - though I think if you add a transition you may get something similar. IMO don't think making EasyZoom respond out of sync to the input would be a better experience so it probably isn't a feature I'd advocate.

**Comment by renzosalvador** [comment]
Thanks Matt!

**Comment by renzosalvador** [comment]
I have manage to move the Y point of the cursor (addHoverOnZoom)  pointer so it matches the main image area. I think that was the solution. Cheers!
