### ISSUE TITLE
[FEATURE] Option to set zoom level

### ISSUE THREAD

**Issue by bh-rat** [i-like-robots/EasyZoom#72]
Hey, great plugin! 
Wanted to know if there is any way to set the zoom level through an input?

**Comment by i-like-robots** [comment]
Thanks for your question @bh-rat. I'm afraid the answer is no, the plugin will always display the full sized image in the zoom flyout. 

I can't see any benefit of overriding the intrinsic size of the zoom image so I wouldn't add that feature but you could easily mimic it yourself using the `scale` CSS transform.

If you mean the ability to manually toggle between different resolutions of the zoom image then I'm afraid not but this could be implemented yourself using the EasyZoom API. f

If you wish to load different resolutions of an image depending on the viewport and/or device then EasyZoom does support srcset.

**Comment by bh-rat** [comment]
Thanks for such a quick reply, I'll look into the scale CSS transform.

**Comment by shahid1579** [comment]
Hi @bh-rat ,
How you did this ?
can you please tell me

**Comment by evgeniyefimchenko** [comment]
.ty-image-zoom {
    &__wrapper {
        display: inline;
    }

    &__flyout {
        opacity: 0;

        transition: opacity var(--image-zoom-animation-time);

        box-shadow: 0 0 8px @base;

        &--visible {
            opacity: 1;
        }

        border: 1px solid @base;

        img {
			zoom: 300%;
            max-width: unset;
        }
    }	
	
}
