### ISSUE TITLE
How to add a class to $flyout img before onShow?

### ISSUE THREAD

**Issue by promptdev** [i-like-robots/EasyZoom#73]
Need to set a class to the generated $flyout image before display.
Is it possible?

**Comment by i-like-robots** [comment]
Sure, after instantiating the plugin the flyout is easily accessible:

```js
// Instantiate EasyZoom instances
var $easyzoom = $('.easyzoom').easyZoom();

// Get an instance API
var api = $easyzoom.eq(0).data('easyZoom');

// Add class to flyout
var api.$flyout.addClass('your-class-name');
```

**Comment by promptdev** [comment]
Great, thanks! I was trying it in different ways without success.

**Comment by promptdev** [comment]
Hey @i-like-robots,
sorry for the late reply and thank you very much for the help.

Was reviewing this and actually the code you posted just applies the class to the $flyout wrapper but not to the image. When logging in the console `api.$flyout` throws an empty div `<div class=​"easyzoom-flyout">​</div>​`.

Does that mean that I cannot apply a class to the image directly?

**Comment by i-like-robots** [comment]
You _can_ but the image element is not created until the first time the user interacts with the zoom.

You could use the `onShow` callback which will only fire after the image has been created and loaded.

```js
$el.easyZoom({
  onShow: function() {
    !this.$zoom.hasClass('your-class-name') && this.$zoom.addClass('your-class-name');
  }
});
```
