### ISSUE TITLE
the image is coming full in easyzoom

### ISSUE THREAD

**Issue by bhawin** [i-like-robots/EasyZoom#74]
I have applied this image as i find it interesting , i am trying to add the code

but here is one problem

whatever image i apply , i get the zoom area as per that image and the image in zoom area which has class "easyzoom-flyout" is coming full width and there is no zoom going

can anyone please help me 

my website url is  http://dev.sparklemuse.com/mobile/index.php?id_product=32&controller=product&id_lang=1&category=3

**Comment by i-like-robots** [comment]
I'm afraid your link no longer works, are you still having problems?

**Comment by bhawin** [comment]
yes , the problem got solved and the link zoom works great , thanks
