### ISSUE TITLE
"The image could not be loaded"

### ISSUE THREAD

**Issue by RadGH** [i-like-robots/EasyZoom#75]
```html
<div class="bt_zoom easyzoom">
	<a href="http://example.com/wp-content/uploads/bt13-ExperienceClipped.png" class="bt_bow_swipebox bt_zoom">
		<img src="http://example.com/wp-content/uploads/bt13-ExperienceClipped-297x780.png" alt="bt13-ExperienceClipped" width="297" height="780">
	</a>
</div>
```

```javascript
jQuery(function($) {
	$('.bt_zoom').easyZoom();
});
```

Tries to load the hover image, says "The image could not be loaded". Chrome's javascript console gives:

```
GET http://example.com/slug-to-a-page/a-child-page/undefined 404 (Not Found)
```

It looks like it's trying to use a relative url. The image, even the thumbnail image, is not in the current directory. Is an absolute url not supported? This is unusable with WordPress, if that's the case.

**Comment by i-like-robots** [comment]
An absolute URL is supported - EasyZoom will [simply attempt to load whatever the value of the link `href` attribute is](https://github.com/i-like-robots/EasyZoom/blob/master/src/easyzoom.js#L77).

What is bt_zoom? Perhaps there is something there that is conflicting.

If you're able to set up a live example I'm happy to take a look.

**Comment by proneta** [comment]
hg
