### ISSUE TITLE
Prevent Images from being downloaded

### ISSUE THREAD

**Issue by promptdev** [i-like-robots/EasyZoom#76]
Hey there @i-like-robots!
Just wondering if you have any suggestions to prevent images from being dragged and downloaded when using EasyZoom With thumbnail images.
I'm not looking for an ultimate solution but rather a simple approach even if its not 100% effective.

**Comment by promptdev** [comment]
More like, do you think something like this could be implemented?

    $(function() {
    var pixelSource = 'http://upload.wikimedia.org/wikipedia/commons/c/ce/Transparent.gif';
    var useOnAllImages = true;
    // Preload the pixel
    var preload = new Image();
    preload.src = pixelSource;
    $('img').live('mouseenter touchstart', function(e) {
        // Only execute if this is not an overlay or skipped
        var img = $(this);
        if (img.hasClass('protectionOverlay')) return;
        if (!useOnAllImages && !img.hasClass('protectMe')) return;
        // Get the real image's position, add an overlay
        var pos = img.offset();
        var overlay = $('<img class="protectionOverlay" src="' + pixelSource + '" width="' + img.width() + '" height="' + img.height() + '" />').css({position: 'absolute', zIndex: 9999999, left: pos.left, top: pos.top}).appendTo('body').bind('mouseleave', function() {
            setTimeout(function(){ overlay.remove(); }, 0, $(this));
        });
        if ('ontouchstart' in window) $(document).one('touchend', function(){ setTimeout(function(){ overlay.remove(); }, 0, overlay); });
    });
    });

**Comment by i-like-robots** [comment]
You're right in thinking there's no ultimate solution, there's no way to prevent somebody getting the file if they want it.

Flickr implement a transparent overlay, I'm sure you could do something similar.
