### ISSUE TITLE
Custom Flyout container

### ISSUE THREAD

**Issue by arsistyle** [i-like-robots/EasyZoom#77]
How select a parent container for Flyout?
else,
how add a custom width to Flyout?

**Comment by arsistyle** [comment]
I add custom width, but the container disappear...


ORIGINAL
.easyzoom--overlay .easyzoom-flyout {
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
}

CUSTOM
.easyzoom--overlay .easyzoom-flyout {
	top: 0;
	left: 0;
	width: 900px;
	height: 100%;
}

**Comment by slindstr** [comment]
Can you add a link with an example? I might be able to help you out. It sounds like the `position` value for the `.easyzoom--overlay` element is something other than `relative` though...

**Comment by arsistyle** [comment]
@slindstr I could do, I could only assign a larger width with percentage, but what I wanted was to change the parent container, to be adapted to the full width of the column I where shown. 

This is de web --> http://locasdeatar.feline.cl/producto.html
