### ISSUE TITLE
Flyout dont appear in IE8

### ISSUE THREAD

**Issue by arsistyle** [i-like-robots/EasyZoom#78]
The zoom doesn't work in IE8, not appear the zoom container (flyout), all other elements work perfectly.
Help :(

**Comment by i-like-robots** [comment]
Thank you for reporting the issue, @arsistyle - this was broken in https://github.com/i-like-robots/EasyZoom/commit/257b122fae635f5174ff0da7b78e8135539feb14 and has been fixed in https://github.com/i-like-robots/EasyZoom/releases/tag/2.3.1

**Comment by arsistyle** [comment]
Thanks, works perfect!
