### ISSUE TITLE
Thumbnails AND toggle

### ISSUE THREAD

**Issue by jonw100** [i-like-robots/EasyZoom#81]
Nice plugin.  I'm attempting to use easyZoom with both the thumbnails functionality and the toggle on/off functionality.

Thumbnails are working fine but I can't get the toggle working on the same element.  I can circumvent my issue a little by removing/adding the easyzoom-overlay class on the toggle click instead but this leaves me with the problem of being unable to scroll the page with a touch device when touching the 'inactive' easyzoom main image (which takes up a considerable portion of the screen)..

I guess I really need to use the teardown and _init methods but I've not been able to manage this successfully.  If I teardown then I lose the thumbnail functionality which needs to be enabled all the time.

Is it possible to have both pieces of functionality on the same element so that thumbnails always work but zoom can be toggled on and off? (and scroll given back to the page whilst zoom is off).  If so can you advise how to do this.

thanks

**Comment by justindantzer** [comment]
@jonw100 I was running into this problem, and for the time being I've come up with a quick fix:

(fairly generic example)
```javascript
var $ez;
var api;
var windowWidth;

$(function(){
    $ez = $('.ez').easyZoom({
            // set your options
        });
    api = $ez.data('easyZoom');

    // teardown/reinit based on window size
    // in my case the breakpoint is 728px wide
    // might be wise to use `setTimeout()` or similar here for teardown/reinit
    $(window).on('resize', function(){
        windowWidth = window.innerWidth
            || document.documentElement.clientWidth
            || document.body.clientWidth;

        if(windowWidth < 728) {
            $ez.data('easyZoom').teardown();
        } else {
            $ez.easyZoom();
        }
    }).trigger('resize');

    // thumbnail handling, referencing the EasyZoom example
    // http://i-like-robots.github.io/EasyZoom/
    $('.thumbnails').on('click', 'a', function(e) {
        e.preventDefault();
        var $this = $(this);

        // check if active
        if(api.isOpen !== undefined){
            // Use EasyZoom's `swap` method
            api.swap($this.data('standard'), $this.attr('href'));
        } else {
            // torn down fallback
            api.$target.find('img').attr( 'src', $this.data('standard') );
            api.$target.find('a').attr( 'href', $this.attr('href') );
        }
    });

});
```

I actually have the image open in a new browser window on click, so i still needed the thumbnail functionality to work when EasyZoom wasn't active
