### ISSUE TITLE
Taking zoomed image URL not from 'href'

### ISSUE THREAD

**Issue by amaltsev** [i-like-robots/EasyZoom#90]
My preview images link to an HTML page that wraps the large image into a header/footer, etc. The EasyZoom code wants to have a bare image in the link "href" attribute. Not a big problem to substitute as needed with javascript, but people right-clicking and selecting "open link in a new tab" bypass the javascript handler and end up with a bare image in their new tab -- something I'd like to avoid.

I will submit my take on solving this in a pull request shortly.

Thanks!

**Comment by i-like-robots** [comment]
Hi @amaltsev, thank you for taking the time to explain your issue and submit the code as well. I can understand where you're coming from but I don't think there is a simple solution... there's really nothing we can do to stop a user from accessing the raw image that I am aware of.

![screen shot 2016-04-17 at 23 41 01](https://cloud.githubusercontent.com/assets/271645/14590574/eb78ab72-04f5-11e6-8774-d4ddfacddba1.png)

The more general utility of providing an alternate source attribute may be useful in other ways. I'll have a think.

**Comment by amaltsev** [comment]
I have no issue with people consciously selecting to view the large image. I may have incorrectly described the problem I was solving -- I just want to a normal click on the image or a middle-click on the image to open that image within the frame of the site.

Here is a case in point, where I used the modified code (sorry for the slightly nsfw theme): http://www.hosieree.com/products/AddictionCamisoleDressAD3009.html -- both the click, the right click and "open in new window", and the middle button click just open the gallery on the same page with that image front and center. That's all there is to it.

By the way, sites that want to hide the image even from "open image in new tab" usually do it by showing an empty div with the image as a css "background-image". It's one more level of obscurity of course, nothing more.

**Comment by i-like-robots** [comment]
@amaltsev That's cool, I think it's a valid feature - just wanted to avoid any promises about 'protecting' images - I know it concerns some.

**Comment by i-like-robots** [comment]
Released 36890d75e66bbd34868aedc319179a82b03f7b70
