### ISSUE TITLE
Not working with imagehandler.ashx 

### ISSUE THREAD

**Issue by teej043** [i-like-robots/EasyZoom#93]
I tried adding an imagehandler.ashx link to an image as the large image but easyzoom can't seem to load this image.

http://www.swedoor.dk/Handlers/ImageHandler.ashx?type=product&typeId=290 

```
<div class="image has-zoom easyzoom" style="text-align:center">
	<a href="http://www.swedoor.dk/Handlers/ImageHandler.ashx?type=product&typeId=290">
		<img src="http://www.swedoor.dk/productThumbs/290_h400/jeld-wen-Indvendige-doere-Compact-Compact-03.jpg" height="381" alt="" />
	</a>
</div>	
```
I was expecting it to work since the other zoom plugins like this uses 'data-' atrribute for the large image and they are working with imageHandler.ashx links.

**Comment by i-like-robots** [comment]
Could you please setup a demo displaying the error?

The following code (the same as used by the plugin) works as expected for me:

```js
var img = new Image();
img.onload = function(e) { console.log(e) };
img.onerror = function(e) { console.error(e) };
img.src = 'http://www.swedoor.dk/Handlers/ImageHandler.ashx?type=product&typeId=290'
```

**Comment by teej043** [comment]
Yes, it does work. My bad, I might have mistaken the error with something else as I must have probably replicated this issue [https://github.com/i-like-robots/EasyZoom/issues/88](https://github.com/i-like-robots/EasyZoom/issues/88).
