### ISSUE TITLE
how to increase the size zoom

### ISSUE THREAD

**Issue by nikosMND** [i-like-robots/EasyZoom#99]
Hello,

Please find the link of my website (prestashop website).
http://mynudesigner.com/fr/sacs-a-main/10-sac-diavolino-xl-noir-imprime-reptile.html

How i can increase the size zoom like your example? 
http://i-like-robots.github.io/EasyZoom/

Indeed, i'd like to have more powerfull zoom effect.

The code of easy zoom  in global css

/**
- EasyZoom core styles
  _/
  .easyzoom {
  position: relative;
  /_ 'Shrink-wrap' the element */
  *display: inline;
  *zoom: 1; }

.easyzoom img {
  vertical-align: bottom; }

.easyzoom.is-loading img {
  cursor: progress; }

.easyzoom.is-ready img {
  cursor: crosshair; }

.easyzoom.is-error img {
  cursor: not-allowed; }

.easyzoom-notice {
  position: absolute;
  top: 50%;
  left: 50%;
  z-index: 50;
  height: 32px;
  line-height: 32px;
  text-align: center;
  width: 32px;
  margin-top: -16px;
  margin-left: -16px;
  background: url(../img/ajax-loader-1.gif) no-repeat center center white;
  -webkit-border-radius: 2px;
  -moz-border-radius: 2px;
  -ms-border-radius: 2px;
  -o-border-radius: 2px;
  border-radius: 2px; }
  .is-error .easyzoom-notice {
    background: #fff; }

.easyzoom-flyout {
  position: absolute;
  z-index: 100;
  overflow: hidden;
  background: #FFF;
  z-index: 7; }
  .easyzoom-flyout img {
    max-width: none;
    width: auto; }

/**
- EasyZoom layout variations
  */
  .easyzoom--overlay .easyzoom-flyout {
  top: 0;
  left: 0;
  width: 100%;
  height: 100%; }

.easyzoom--adjacent .easyzoom-flyout {
  top: 0;
  left: 100%;
  width: 100%;
  height: 100%;
  margin-left: 20px; }

Thanks in advance for your help and congrats for your project.

Nikos
mynudesigner.com

**Comment by i-like-robots** [comment]
The zoom image in the page you link to is not much larger than the standard image. The zoom image will be displayed at its natural size.

Standard image:
http://mynudesigner.com/32-big_default/sac-diavolino-xl-noir-imprime-reptile.jpg (548x649)

Zoom image:
http://mynudesigner.com/32-thickbox_default/sac-diavolino-xl-noir-imprime-reptile.jpg (700x800)

I'd recommend the zoom images be at least 1.5x larger than the standard image, or even better 2x. In this case the zoom image is only 1.28x larger.

**Comment by nikosMND** [comment]
Thanks a lot for your answer.
I have modified the size of zoom image in prestashop (thickbox defaut), the size is 1096x1298.
After that, i have regenerated the images on prestashop and clean the memory cache of prestashop.

For the moment, it's the same size zoom on my website.
 Thanks in advance.
Best.

Nikos

**Comment by nikosMND** [comment]
What do i have to do now? I have modified the size image (thickbox defaut) and the size of zoom is the same.
Thanks in advance for your help.

Best.
Nikos

**Comment by i-like-robots** [comment]
The zoom image is still the same size, I'm afraid: http://mynudesigner.com/32-thickbox_default/sac-diavolino-xl-noir-imprime-reptile.jpg (700x800)

I'm not familiar with Prestashop so I'm afraid I can't offer any advice,
